name: Run hehe

on:
  workflow_dispatch:
  schedule:
    # This will run the action every day at 00:00 UTC.
    - cron: "6 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run Janitor
        run: go run main.go
        env:
          SECRET_XATA_PG_ENDPOINT: ${{ secrets.SECRET_XATA_PG_ENDPOINT }}
